### PR TITLE
Modify example branch to version 1.12.x

### PR DESCRIPTION
**Pull request by rvlieshout**
Previous instructions told you to use 1.0.x

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @rvlieshout isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by rvlieshout** [comment]
Signed it

2018-06-20 8:29 GMT+02:00 The Linux Foundation <notifications@github.com>:

**Comment by LisaFC** [comment]
I've merged this in but we should really have the version as a variable unless we want to keep updating the page every time the version we want the user to use changes - @jtattermusch? Anyone else?

**Comment by carl-mastrangelo** [comment]
@LisaFC  On the main grpc/grpc repo we have:

`git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc`

Less easy to read, and doesn't work on windows, but it does avoid the churn.

**Comment by rvlieshout** [comment]
@carl-mastrangelo If it doesn't work on Windows, then you might offend a lot of C# (target of this example) developers :grinning:

**Comment by carl-mastrangelo** [comment]
@rvlieshout Yeah, I think a better long term solution would be to make a "latest" branch in the repo, and merge in whatever the latest release is.  That way there is always a consistent command line example.  

(also, I don't think every system comes with curl!)

**Pull request merged**
