### PR TITLE
Add a link to Apache BookKeeper which also uses gPRC

### PR DESCRIPTION
**Pull request by sijie**
Apache BookKeeper uses gRPC in its table service, thus adding the link to it.

Signed-off-by: Sijie Guo <sijie@apache.org>

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @sijie isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by sijie** [comment]
I just signed the CLA :)

**Comment by sijie** [comment]
thank you @carl-mastrangelo 

I just rebased to master HEAD

**Comment by carl-mastrangelo** [comment]
@sijie Merged, Thanks!

**Pull request merged**
