### PR TITLE
Fix incorrect param name

### PR DESCRIPTION
**Pull request by gnomeby**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @gnomeby isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by gnomeby** [comment]
Signed Up CLA

**Comment by carl-mastrangelo** [comment]
@gnomeby Thanks!   Merging now.

BTW, do you know what you were able to do to get CLA bot working?

**Comment by gnomeby** [comment]
> BTW, do you know what you were able to do to get CLA bot working?

No idea.

**Pull request merged**
