### PR TITLE
Add a missing word in cpp documentation

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @orgads isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by orgads** [comment]
signed

**Comment by carl-mastrangelo** [comment]
@orgads I believe you need to do some other steps to get the CLA signed.  There should be a website to have to click stuff, and an email that describes the process.

**Comment by orgads** [comment]
I signed it

**Comment by carl-mastrangelo** [comment]
cc: @hsaliak @srini100

**Comment by orgads** [comment]
I signed it

**Comment by carl-mastrangelo** [comment]
@orgads Merged, Thanks!

**Pull request merged**
