### PR TITLE
Update android.md

### PR DESCRIPTION
**Pull request by raymondr**
Define variable failed that was used but not defined.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @raymondr isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by ericgribkoff** [comment]
Thanks for sending this out. So our actual example defines `failed` as a class member variable, so it's declared outside of the snippets seen on this page: see [here](https://github.com/grpc/grpc-java/blob/8d3d26dda109d70467092b15c980a2bbfffc6e55/examples/android/routeguide/app/src/main/java/io/grpc/routeguideexample/RouteGuideActivity.java#L259) and [here](https://github.com/grpc/grpc-java/blob/8d3d26dda109d70467092b15c980a2bbfffc6e55/examples/android/routeguide/app/src/main/java/io/grpc/routeguideexample/RouteGuideActivity.java#L352). But it looks there isn't any reason for them to be defined at the class level instead of inside the methods as you have done here, so if you'd like to send a PR to the gRPC Java repo updating the example code then we can also merge this documentation change.

**Comment by carl-mastrangelo** [comment]
@raymondr can you respond to @ericgribkoff 's comments?  I'd prefer to not have long open PRs.

**Comment by thisisnotapril** [comment]
Closing due to age and lack of CLA

**Pull request closed without merging**
