### PR TITLE
Update java.md

### PR DESCRIPTION
**Pull request by elenabdc**
In windows it you get an error if you don't delete de build directory.

### CODE REVIEW

**Comment by elenabdecastro** [comment]
I signed it!

**Comment by carl-mastrangelo** [comment]
@elenabdc I think this is not needed, the build directories should be difference since ./gradlew is build from the examples/ directory. 

Is this not the case?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @elenabdc isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thisisnotapril** [comment]
Closing due to age

**Pull request closed without merging**
