### PR TITLE
fix typo: s/uses case/use case/

### PR DESCRIPTION
**Pull request by al-maisan**

### CODE REVIEW

**Comment by hsaliak** [comment]
LGTM

**Comment by hsaliak** [comment]
@al-maisan could you sign the Google CLA so I can accept this and merge?

**Comment by hsaliak** [comment]
@al-maisan we'd really like to accept this contribution if you are able to sign and verify the CLA. Thanks!

**Comment by thisisnotapril** [comment]
Closing due to no CLA.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
