### PR TITLE
Avoid errors when do `docker-compose pull`

### PR DESCRIPTION
**Pull request by dkotrada**
Error on Windows when not logged in. Developer needs to be logged in before executing `docker-compose pull`

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @dkotrada isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by dkotrada** [comment]
Signed

**Comment by dkotrada** [comment]
...

**Review by stanley-cheung — APPROVED** [review]
LGTM

**Comment by stanley-cheung** [comment]
@dkotrada Can you make sure you sign the CLA with the email address you make the git commit in please? Thanks!

**Comment by dkotrada** [comment]
I use everywhere same email. I signed with my github account to linux CLA

**Comment by thisisnotapril** [comment]
@dkotrada can you file a support ticket with CNCF to have them look at the CLA? https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/88

**Pull request closed without merging**
