### PR TITLE
lowercase 'c' in 'credentials' in Node GRPC lib

### PR DESCRIPTION
**Pull request by tejasmanohar**
# Proof

_index.js_

``` js
const grpc = require('grpc');
console.log(grpc.Credentials);
console.log(grpc.credentials);
```

_..._

``` sh
$ node index.js
undefined
{ createSsl: [Function],
  createFromMetadataGenerator: [Function],
  createFromGoogleCredential: [Function],
  combineChannelCredentials: [Function],
  combineCallCredentials: [Function],
  createInsecure: [Function] }
$ npm ls | grep grpc
├─┬ grpc@0.15.0
```

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Signed.
screen shot 2016-07-05 at 11 56 32 pm

**Comment by murgatroid99** [comment]
LGTM

**Comment by thisisnotapril** [comment]
Closing; this was dup'd in #359

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @tejasmanohar isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
