### PR TITLE
add rust doc

### PR DESCRIPTION
**Pull request by siddontang**
Hi

We embed the C gRPC in Rust and build the Rust version [grpc-rs](https://github.com/pingcap/grpc-rs).

It has been running in our project in production for a long time, so we think it is stable and can let other Rustaceans use it.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @siddontang isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by mit-mit** [comment]
I don't think I'm the right reviewer for this; paging @jtattermusch

**Comment by nicolasnoble** [comment]
Ah, sorry @mit-mit, I'm mixing up languages :-)

**Comment by srini100** [comment]
@siddontang, can you please rebase your branch?

**Comment by hsaliak** [comment]
@ctiller fancy helping with an open source contribution? :) Let me know if you will / will not be able to review these docs..

**Comment by hsaliak** [comment]
@siddontang thanks for this pull request. 
Some questions on the Rust implementation - does it have full interop coverage? (Looks like it has interop tests)? gRPC currently has a 6 week release cycle and we officially try to support up to the previous release. Do you think that the rust implementation would be able to track to the latest stable release? 

The reason I am asking this is that before we can state broadly that this is a supported contribution, I want to ensure that the project can track the core development branch closely and implement all the important features.

**Comment by hsaliak** [comment]
@siddontang it looks like you folks have forked gRPC - this is a painful strategy especially if you are patching directly. For example, 1.13 is around the corner already. 
Any chance you can just sub-module core gRPC? 
Have you filed issues for needed features that were removed? If so can you please point them to me?

@vjpai do you know the history behind the alarm feature mentioned here?

**Comment by siddontang** [comment]
Hi @hsaliak 

We know that it is not a good idea to fork the gRPC project. Another way is that after your C++ core refactor is finished, we can wrap a C API around it like many other projects (LevelDB, RocksDB) do. 

The alarm feature is removed from  1.10, https://github.com/grpc/grpc/releases/tag/v1.10.0. Sorry that we didn't file an issue for it, just thought it's your plan.

**Comment by siddontang** [comment]
@hoverbear

Now we can support the latest gRPC, so I think it is better for us to continue.

**Comment by Hoverbear** [comment]
We have recently merged https://github.com/pingcap/grpc/pull/14 to support 1.14.2. 

@siddontang seems that @hsaliak would like to know if we can promise to always track the latest release. This means we'd need to upgrade our library every 6 weeks.

@hsaliak can you help me understand what kind of timeline is expected for the upgrade? When GRPC releases a new version how fast is it expected that our library would also update?

**Comment by hsaliak** [comment]
@Hoverbear @siddontang thanks for all the work! 
To answer your question -- grpc supports the latest release and the one prior. That is latest and (n-1) minor version. However it is stable in terms of interop and functionality. 

We would need some understanding of how closely you want to track the releases. 

The reason for that is, if we refer to the external project, we want to ensure that it meets a good enough bar (and would like to work with you folks to make sure this is the case).

Some questions
1) What is the testing you folks do, do you run our interop tests?
2) Do you folks run continuous tests
3) Is the API considered stable?
4) Could you point us to the reference docs -- rustdoc or similar?

Would you folks be OK at some point to move this project to grpc-ecosystem org? It's not a requirement, but wanted to check. 

Also, let us know if you want to chat about this in VC or something similar, we would be happy to.

**Comment by overvenus** [comment]
Hi @hsaliak 

Another grpc-rs developer here.

> 1. What is the testing you folks do, do you run our interop tests?

Yes, we have implemented and passed interop tests. Also we implement a `qps_worker` to benchmark grpc-rs wiht grpc's performance tests.

> 2. Do you folks run continuous tests

Yes, we run Travis CI(linux and macOS) and Appveyor CI(windows) on master branch and on PRs.

 > 3. Is the API considered stable?

Most of them are stable, however we do change few APIs. We follow Semantic Versioning, bumps major version after introduced some breaking changes, so they does not break users build.

> 4. Could you point us to the reference docs -- rustdoc or similar?

Yes, we are very happy to! :smile: 

> We would need some understanding of how closely you want to track the releases.

Currently, tracking the latest relaese is not the first priority for us, the stability is, because we are short of hands. We upgrade the grpc core library about every 4 versions, we can speed up if you want.

**Comment by Hoverbear** [comment]
Here are the current release docs: https://docs.rs/crate/grpcio

**Comment by Hoverbear** [comment]
@hsaliak It's been a couple weeks, so just wanted to politely ping you to see if you had any feedback. :)

**Comment by thisisnotapril** [comment]
@hsaliak can you review this one please? trying to determine if we should leave it open for the site migration or not.

**Comment by chalin** [comment]
@siddontang @srini100 et all: is this work something that you'd like to revive, but in the context of the [new repo (grpc/grpc.io)](https://github.com/grpc/grpc.io)?

cc @thisisnotapril

**Comment by chalin** [comment]
I'm going to close this PR since this repo is inactive. If any of you would like to respond to my question from earlier, please do so here: https://github.com/grpc/grpc.io/issues/354.

**Pull request closed without merging**
