### PR TITLE
Add quotes around title because ':'

### PR DESCRIPTION
**Pull request by kkm000**
Looks like a table now: https://github.com/kkm000/grpc.github.io/blob/9270535dedf73da44a66cb3d2d8d37d5cf1e7af3/_posts/2018-18-18-grpc-dotnet-build.md

### CODE REVIEW

**Comment by kkm000** [comment]
Let's push and see if that works. If not, I'll do the `&#58;` trick. Seems that no one reported it as not working, other reports are ambiguous.

**Comment by jtattermusch** [comment]
I got this error:

```
The page build failed for the `master` branch with the following error:

The file `_posts/2018-18-18-grpc-dotnet-build.md` does not have a valid date in the filename. For more information, see https://help.github.com/articles/page-build-failed-invalid-post-date/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by kkm000** [comment]
Ugh. It's 12-18. I'll make another PR.

**Comment by kkm000** [comment]
#799. I did the '&#58;' trick, just seems safer.

**Pull request merged**
