### PR TITLE
c.md - Fix erroneous use of CreateChannel

### PR DESCRIPTION
**Pull request by vdamle**
- CreateChannel does not accept ChannelArguments
- Adds reference to CreateCustomChannel to specify ChannelArguments

### CODE REVIEW

**Comment by vdamle** [comment]
I signed it!

**Comment by hsaliak** [comment]
@vjpai can you take a quick look?

**Comment by vdamle** [comment]
Thanks for approval @vjpai . @hsaliak  - Status still says "Merging is blocked - Merging can be performed automatically with one approved review".

**Comment by hsaliak** [comment]
Thanks for the PR - merged

**Pull request merged**
