### PR TITLE
Fix typo in node.md

### PR DESCRIPTION
**Pull request by uraway**
just fix typo:
occured → occurred

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @uraway isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by uraway** [comment]
I signed it

**Comment by thisisnotapril** [comment]
@uraway can you please resign the CLA for this? Thanks!

**Comment by chalin** [comment]
Finally applied this change to the new site via https://github.com/grpc/grpc.io/pull/353. 😄

**Pull request closed without merging**
