### PR TITLE
Wrote up a quick recap of todays meeting notes for the blog

### PR DESCRIPTION
**Pull request by mjpitz**
Let me know if any edits need to be made.

### CODE REVIEW

**Comment by jpitz** [comment]
@thisisnotapril : I updated the java release notes call out since they are now available

**Comment by jpitz** [comment]
Bump on this merge.

**Comment by thisisnotapril** [comment]
Closing because of age and I totally dropped the ball

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
