### PR TITLE
Update python.md

### PR DESCRIPTION
**Pull request by ofrancois**
Minor wording issue.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ofrancois isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by carl-mastrangelo** [comment]
@kpayson64 can you take a look?

**Comment by hsaliak** [comment]
@ofrancois any chance you can take a look at signing the CLA so we can merge this PR?

**Comment by thisisnotapril** [comment]
Closing due to age and lack of CLA

**Pull request closed without merging**
