### PR TITLE
fix example code in the documentation

### PR DESCRIPTION
**Pull request by omigamedev**
InsecureCredentials() is now InsecureChannelCredentials()

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @omigamedev isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
Please sign the CLA, otherwise I cannot merge.

**Comment by jtattermusch** [comment]
Also, if you could rebase, it would be nice (for cleaner commit history).

**Comment by omigamedev** [comment]
Just signed the CLA, but I'm not sure how to rebase.

**Pull request merged**
