### PR TITLE
java.md: Fix typo

### PR DESCRIPTION
**Pull request by perlun**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @perlun isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by carl-mastrangelo** [comment]
@perlun Change looks good, but our org requires a CLA before we can merge.  Can you check your inbox after clicking the link?

**Comment by perlun** [comment]
@carl-mastrangelo Sure, signed now. (even though I think requiring a CLA for this kind of change is somewhat extreme. :wink:)

**Comment by carl-mastrangelo** [comment]
@perlun I agree, but lawyers.

**Comment by carl-mastrangelo** [comment]
Merged, thanks!

**Pull request merged**
