### PR TITLE
Remove ref to more docs coming soon

### PR DESCRIPTION
**Pull request by LisaFC**
Fixes https://github.com/grpc/grpc.github.io/issues/296

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum; thanks.

**Comment by LisaFC** [comment]
Gah, just realized I merged into master rather than the GA branch. No harm done, I'll just do another PR...

**Comment by nathanielmanistaatgoogle** [comment]
Oof; that means that I as reviewer failed to check that the proper branch was targeted. I am chastened.

**Comment by pgrosu** [comment]
Well, we're a welcome community, so everything is forgiven - everyone can still have cake :)

**Pull request merged**
