### PR TITLE
Define the IDL acronym on first use.

### PR DESCRIPTION
**Pull request by niroyb**
It's nice to define acronyms on first use, especially on getting started docs.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @niroyb isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by hsaliak** [comment]
@niroyb could you please sign the CLA so we can merge this?

**Comment by niroyb** [comment]
I get that I am already allowed to contribute:

Thanks

Nick

**Comment by hsaliak** [comment]
Thanks for the contribution!

**Pull request merged**
