### PR TITLE
Bump java to v1.13.1

### PR DESCRIPTION
**Pull request by dapengzhang0**

### CODE REVIEW

**Comment by dapengzhang0** [comment]
@ejona86 PTAL

**Comment by ejona86** [comment]
I don't see the version on maven central yet (I'm not talking about search.maven.org). If you've published the binaries, I don't think they've replicated yet.

**Comment by dapengzhang0** [comment]
Let's wait ~1 day.

**Comment by LisaFC** [comment]
Are we ok to merge?

**Comment by ejona86** [comment]
No. The release still hasn't appeared. It seems there's a release problem we're tracking down.

**Pull request merged**
