### PR TITLE
Added Go authentication example

### PR DESCRIPTION
**Pull request by bbengfort**
Simple examples in the style of the other, less verbose examples -- just to get the ball rolling.

### CODE REVIEW

**Comment by bbengfort** [comment]
I signed it!

**Comment by jadekler** [comment]
Ping @dfawley

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @bbengfort isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by dfawley** [comment]
Wow, thanks for sticking around, 1 year later.  Sorry nobody ever looked at this.

https://grpc.io/docs/guides/auth.html now has Go examples after #638 and #651.  If you feel those are insufficient, feel free to rebase and update this PR, otherwise we can close it.

**Comment by bbengfort** [comment]
@dfawley feel free to close it in that case - looks like the #638 covers what I did here.

**Comment by dfawley** [comment]
:+1:

Thanks again for the contribution!

**Pull request closed without merging**
