### PR TITLE
Correct usage of server streaming RPC calls in Node

### PR DESCRIPTION
**Pull request by eatonphil**
Since https://github.com/grpc/grpc/issues/8954 was fixed, it doesn't seem like the `'end'` event is actually sent. This also adds documentation on errors and error-handling semantics.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @eatonphil isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by eatonphil** [comment]
Signed the CLA.

**Comment by murgatroid99** [comment]
This change is not really correct. In normal operation, an `end` event will be fired at the end of the stream as documented. The change from that linked issue means that if there is an error, then there won't be an end event.

**Comment by eatonphil** [comment]
@murgatroid99 got it, thanks. Will update.

**Comment by murgatroid99** [comment]
OK, this looks more accurate, but I don't see why you want to add the sentence "Errors in the `'data'` callback will not cause the stream to be closed." In general, errors in user code won't affect the stream state, and I don't think it's necessary to call out that specific event.

**Comment by eatonphil** [comment]
I think it's better to be explicit, the way it's set up does not make it clear whether errors in the data callback will cause the stream to be cancelled or not. I only saw what really happens when I tried it. There's no reason not to document that. A different library could choice to await Promises returned by the callback and close the stream if it failed. Either way seemed reasonable to me.

**Comment by eatonphil** [comment]
ping

**Comment by eatonphil** [comment]
Anything more I can do to get this merged?

**Comment by murgatroid99** [comment]
Apparently someone else needs to approve this. @hsaliak can you do that?

**Pull request merged**
