### PR TITLE
Rename invalid date 18-18 to 12-18; use &#58;` for  the `:`

### PR DESCRIPTION
**Pull request by kkm000**
Fix both, to be on the safe side.

### CODE REVIEW

**Comment by kkm000** [comment]
*Now* I understand what @carl-mastrangelo  meant by "wonky"!!! :)

**Comment by kkm000** [comment]
Magic!!! It worked :-)) Thanks!

**Comment by jtattermusch** [comment]
Things are looking good now: https://grpc.io/blog/ Thanks for taking the time to write the blogpost.

**Comment by kkm000** [comment]
Links are also ok, point to expected places, except that suddenly removed MS recommendation. Do not really know what to do with it. Maybe nothing--it's external. I can also point it to a pre-removal version on GitHub. What's your take on it? Leave as is or redirect?

**Pull request merged**
