### PR TITLE
standardize path resolution for usage of githuburl variable

### PR DESCRIPTION
**Pull request by nilslice**
fixes Github 'Edit' links on docs pages where a `//` is introduced, i.e.
`https://github.com/grpc/grpc.github.io//edit/master/docs/index.html`

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @nilslice isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by nilslice** [comment]
CLA signed... pending system auto-update (unsure of delay). Thanks!

**Comment by thisisnotapril** [comment]
@nilslice old PR here, wanted to check if you thought it was ready to go or if we should close for now? We're planning to move the site to Hugo soon and trying to clean up PRs before doing so. Thanks!

**Comment by nilslice** [comment]
@thisisnotapril - I believe this is still addressing an issue where links are occasionally broken because of inconsistency in the URL path. The PR makes these consistent. But, I can't build the blog anymore due to some old jekyll & bundler issues, so I can't verify 😆 

Should be fine to merge, but it will also be OK to just close this if a new Hugo theme and config will replace the current site.

Thanks for checking!

**Comment by thisisnotapril** [comment]
@nilslice gotcha, thank you! I'm going to go ahead and close this for now and we can reopen post Hugo migration if needed.

**Pull request closed without merging**
