### PR TITLE
pass channel credentials as byte string

### PR DESCRIPTION
**Pull request by ysangkok**
As documented on https://grpc.io/grpc/python/grpc.html#grpc.ssl_channel_credentials

### CODE REVIEW

**Comment by ysangkok** [comment]
OK, I signed

**Comment by carl-mastrangelo** [comment]
cc: @lidizheng

**Comment by lidizheng** [comment]
@ysangkok The changes are good, and they prevent Python3 users from failing. Can you make the same changes for the server part as well?

**Comment by carl-mastrangelo** [comment]
@lidizheng If you are happy I can merge.

**Comment by carl-mastrangelo** [comment]
@ysangkok Merged, Thanks!

**Pull request merged**
